#!/usr/bin/perl

use strict;

my $filename = shift;

open(LIN,"<","$filename.lin") or die("unable to open $filename.lin: $!");
my(@slopes);
while(<LIN>) {
  chomp();
  my(@c) = split(/ /);
  if(@slopes) {
    $slopes[-1]{end_clock} = $c[0];
  }
  push(@slopes, {
    slope => $c[2],
    intercept => $c[3],
    source_clock => $c[0]
  });
}
close(LIN);

open(POINTS,"<","$filename") or die("unable to open $filename: $!");
while(<POINTS>) {
  chomp();
  my(@c) = split(/ /);
  if(defined($slopes[0]{end_clock}) and ($slopes[0]{end_clock} <= $c[6])) {
    shift(@slopes);
  }
  my $prediction = $c[6]*$slopes[0]{slope} + $slopes[0]{intercept};
  my $diff = $c[5] - $prediction;
  print "$c[6] $prediction $diff ".$slopes[0]{slope}." ".$slopes[0]{intercept}."\n";
}
close(POINTS);
